### ISSUE TITLE
Timeout issues trying to connect to AWS Redis Cache instance

### ISSUE THREAD

**Issue by icodetlrn** [steve0511/resty-redis-cluster#103]
Hi,

I am using below configuration code to connect AWS redis cache instance

```bash
local config = {
    dict_name = "test_locks",               --shared dictionary name for locks, if default value is not used 
    refresh_lock_key = "refresh_lock",      --shared dictionary name prefix for lock of each worker, if default value is not used 
    name = "testCluster",
    serv_list = {
        { ip = "<aws-hostname-url>", port = <aws-host-port> },
    },
    keepalive_timeout = 60000,
    keepalive_cons = 1000,
    connect_timeout = 1000,
    read_timeout = 1000,
    send_timeout = 1000,
    max_redirection = 5,
    max_connection_attempts = 1
}

local redis_cluster = require "rediscluster"
local red_c = redis_cluster:new(config)
```

But when using above code to write or read the red_c client gives error, saying "unable to write to closed socket connection".
Which means that the connection was not successful.

Is there some missing configuration I am missing in this setup.

As an update for the the ticket, in the stack trace i get below error :

` rediscluster.lua:238: fetch_slots(): failed to fetch slots: timeout`

Though connection to instance works through redis cli or through a java library.

Regards,
Akash

**Comment by icodetlrn** [comment]
Closing the ticket, as issue is now resolved for me.

**Comment by khangt1k25** [comment]
Hi @icodetlrn, i am facing this problem exactly. How can you fix that? Thank you

**Comment by icodetlrn** [comment]
Hi @khangt1k25

You can try below config : 

```
redis_cluster = require "rediscluster"

local redis_hostname = ''
local redis_port = 9292
local redis_auth = 'password'

config = {
    name = "test-cluster",
    serv_list = {
        { ip = redis_hostname, port = redis_port }
    },
    keepalive_timeout = 60000,
    keepalive_cons = 1000,
    connect_timeout = 1000,
    max_redirection = 5,
    max_connection_attempts = 1,
    auth  = redis_auth,
    connect_opts = {
        ssl = true,
        ssl_verify = false,
        server_name = redis_hostname,
        pool = "redis-cluster-connection-pool",
        pool_size = 20,
        backlog = 10
    }
}
```
Above i am using "rediscluster" now, you can add the contents of "rediscluster.lua" from [here](https://github.com/api7/lua-resty-redis-cluster/blob/devel/lib/resty/rediscluster.lua)
