### ISSUE TITLE
remove c dependency

### ISSUE THREAD

**Issue by hbagdi** [steve0511/resty-redis-cluster#11]
Hi @steve0511 
`redis_slot.c` currently is used to calculate the slot.
Is there a blocker for to convert this piece code into Lua?
I'm assuming here that we use C here for performance reasons only. Correct me if I'm wrong.

**Comment by steve0511** [comment]
Hi @hbagdi 
yes, it's only for performance reasons. I believe it's not blocker to convert into Lua.

**Comment by hbagdi** [comment]
Hi @steve0511 
Have you measured Lua vs C performance for slot calculation?
Also, is there some obvious expectation that Lua would perform bad (in comparison to C) for this use case.
I'm new to the Lua world.

**Comment by steve0511** [comment]
We have a test and shows C has about 40%-50% win than Lua for CRC16 calculation. 
My major language is not Lua so I cannot 100% list the case Lua must lose to C, but as the experience for cases like regular expression match, string split lua didn't play so well and it is recommended to use FFI and C.

**Comment by steve0511** [comment]
Close as of now.
