### ISSUE TITLE
pick_node returns slave node for write commands 

### ISSUE THREAD

**Issue by tyiss** [steve0511/resty-redis-cluster#13]
when `enableSlaveRead = true`, pick_node sometimes returns a readonly slave, for commands that is not readonly. e.g. `set`, `sadd`, etc.

**Comment by steve0511** [comment]
Hi

Yes enableSlaveRead shall always be used at readonly scenario for redis cluster slave node is readonly.

Update document for this case.

**Comment by steve0511** [comment]
close as of now
