### ISSUE TITLE
Example makefile or instruction on how to generate the *.so file?

### ISSUE THREAD

**Issue by hlee-va** [steve0511/resty-redis-cluster#14]
Hi, Nice work! We really want to try it out in our current project. Would you mind giving an example Makefile or some instructions for compiling and linking the `redis_slot.so`

**Comment by steve0511** [comment]
Hi Hlee

redis_slot.so could be generated by sample:

 gcc redis_slot.c -fPIC -shared -o redis_slot.so -l /usr/local/include/luajit-2.1(replace with local luajit path)

**Comment by hlee-va** [comment]
Thanks Steve! Ima try that!!
