### ISSUE TITLE
help: attempt to index a nil value

### ISSUE THREAD

**Issue by ngxlua** [steve0511/resty-redis-cluster#17]
感谢作者提供 redis cluster 的代码

但我在使用时，始终出现错误，就像这样:

```
[error] 8054#8054: *139 lua entry thread aborted: runtime error: ...e/openresty/nginx/app/lib/resty/rediscluster.lua:269: attempt to index a nil value
stack traceback:
coroutine 0:
	...e/openresty/nginx/app/lib/resty/rediscluster.lua: in function 'handleCommandWithRetry'
```

**Comment by ngxlua** [comment]
@steve0511 感谢回复，我后来发现代码里是未处理认证导致使用错误

**Comment by steve0511** [comment]
可以使用red:get_reused_times 判断connection是否已经通过验证，具体可以参考这里
http://wiki.jikexueyuan.com/project/openresty/redis/auth_connect.html

确实当前的client还没加authenticate feature, 我们后面会把这部分补下(这段实在比较忙不好意思)

**Comment by ngxlua** [comment]
@steve0511 明白了， 非常感谢。
