### ISSUE TITLE
报找不到 cluster 方法

### ISSUE THREAD

**Issue by MiluDeer** [steve0511/resty-redis-cluster#21]
openresty/1.9.7.4

rediscluster.lua:105: attempt to call method 'cluster' (a nil value)

是不是需要其他库

**Comment by steve0511** [comment]
local redis = require "resty.redis"

你引入resty redis了吗？https://github.com/openresty/lua-resty-redis

**Comment by MiluDeer** [comment]
引入了

在 common_cmds 里加上 cluster 才可以

**Comment by lonstanley** [comment]
> 引入了
> 
> 现在解决了， 在 common_cmds 里加上 "cluster" 就可以了

请问是怎么解决的，我碰到了同样的问题。是在哪里加上 cluster？

**Comment by lonstanley** [comment]
哦，知道了，是要改 resty.redis 里面的 cmds
