### ISSUE TITLE
do I need to close the connection?

### ISSUE THREAD

**Issue by moshufenmo** [steve0511/resty-redis-cluster#22]
Thanks for your code, we need it in deep.

after execute the command, do I need to close the connection manually?  like keep-alived or close ? how to call these methods ?  can u show some examples ?

Thanks.

**Comment by steve0511** [comment]
You don't need to close the connection, client is based on lua-resty-redis and will set keep-alive by itself

**Comment by steve0511** [comment]
close as of now.

**Comment by moshufenmo** [comment]
> You don't need to close the connection, client is based on lua-resty-redis and will set keep-alive by itself

You said this client is based on lua-resty-redis, I don't need to close the connection manually, but lua-resty-redis has method named close/keep-lived, it's also a good hobbit to close the connection in time, right? if I don't close the connection in time, it will be closed during GC. Is that will impact the performance? or something else?
