### ISSUE TITLE
generate redis_slot.so from redis_slot.c (can done by gcc)

### ISSUE THREAD

**Issue by zhaoxm8023** [steve0511/resty-redis-cluster#28]
please compile and generate redis_slot.so from redis_slot.c (can done by gcc)
这一步怎么做 求详细指导 小白一个。。。

**Comment by shuxiao9058** [comment]
gcc -O2 -shared -fPIC -Wall -pedantic -I/usr/local/openresty/luajit/include/luajit-2.1/   -I/usr/local/openresty/luajit/include/luajit-2.1/  redis_slot.c -o redis_slot.so
