### ISSUE TITLE
Custom commands for redis

### ISSUE THREAD

**Issue by AlexProfi** [steve0511/resty-redis-cluster#29]
Hi 
How run custom commands?
I use this
```
local res, err = red_c:keys("*")
```
but get only one key in result. However I add 2

For get DBSIZE I run
```
 local res, err = red_c:dbsize()
```
But get 
ERR wrong number of arguments for 'dbsize' command
Does this plugin support functions of redis: keys, dbsize, flushdb?

**Comment by steve0511** [comment]
I test keys * and dbsize but no problem here. Please note dbsize and keys * only apply to specific node but not the while cluster.

**Comment by steve0511** [comment]
Can you attach your whole parts of code?

**Comment by AlexProfi** [comment]
Perhaps I need redis sentinel in that case/ because i need all keys at the each instance of redis

**Comment by steve0511** [comment]
Hi, I think you don't need to add keys/dbsize commands explicitly, just call directly is ok.

**Comment by AlexProfi** [comment]
It gets keys only from one master not all
Or it is specification of redis cluster and impossible to get all keys in cluster

**Comment by steve0511** [comment]
Yes, it's specification of redis cluster. Only way is implement by ourselves in client side. The idea is not complex, get all master from every shard, execute and aggregate the result.

**Comment by steve0511** [comment]
Close as of now.
