### ISSUE TITLE
Performance improvement. Redis cluster config is updated per request.

### ISSUE THREAD

**Issue by vkozubal** [steve0511/resty-redis-cluster#3]
Hi there.
Right now we perform slot initialization on each requst.
How we can update redis cluster config once in several minutes.(time could be configurable)
Maybe you can point how it could be implemented?

**Comment by steve0511** [comment]
Hi, did you set lua_code_cache on? if so, slot cache should only be reset on
1.   first request
2.  get moved redirection
3.  there is node connection error.

**Comment by vkozubal** [comment]
Yes. You are right. All cases work as handled in the code. Thanks.
