### ISSUE TITLE
set weight to different server

### ISSUE THREAD

**Issue by l36t** [steve0511/resty-redis-cluster#35]
serv_list = {                      
        { ip = "192.168.1.1", port = 7001 },--weight:5
        { ip = "192.168.1.1", port = 7002 },
        { ip = "192.168.1.2", port = 7001}, --weight:10
        { ip = "192.168.1.2", port = 7002 },
      }
when I set serv_list,can I set different  weight to different server  
Thanks

**Comment by steve0511** [comment]
There is no weight in redis cluster specification.
Also client will not support that.
