### ISSUE TITLE
Simplify shared memory allocation for redis cluster lock.

### ISSUE THREAD

**Issue by vkozubal** [steve0511/resty-redis-cluster#4]
I tested 
`lua_shared_dict redis_cluster_slot_locks 100k;`
approach with memory allocation on my test project with simple nginx config and it was working fine.
But now I use different nginx config in production project and I am having a hard time to allocate shared memory with this directive.

I have tried to put it in different parts of my config and error is different 
`emerg] the shared memory zone "redis_cluster_slot_locks" is already declared for a different use in /var/www/path/config/lua.conf:9`
which is declared in the single place

or this (looks like memory wasn't initialized and I get )
`[lua] rediscluster.lua:137: init_slots(): failed to create lock in initialization slot cache: dictionary not found while handling client connection, client: 172.19.0.1, server: 0.0.0.0:9999`
Config contains several includes. 

Is it possible to move this config directive logic into the code so it doesn't need configuration in the config file?

**Comment by steve0511** [comment]
Hi, resty lock always depend on shared dictionary. https://github.com/openresty/lua-resty-lock

have you tried to increase memory?

**Comment by vkozubal** [comment]
Hi, I tried to change `10m` and it didn't help.

**Comment by vkozubal** [comment]
so basically when I create 

`
lua_shared_dict redis_cluster_slot_locks 10m;
server {

    listen 85 default_server deferred;
     location /test-redis {
  content_by_lua_block{
...
`
it works as expected. But when I use it from the service started in `content_by_lua_block` it doesn't work.

init_by_lua_block {
  require('runner').init('device')
}

init_worker_by_lua_block {
  require('runner').worker()
}

server {
  listen xxx reuseport backlog=1024 ; 

  content_by_lua_block {
    require('runner').service()
  }
}
Would appreciate some hints how I can overcome this problem

**Comment by steve0511** [comment]
Hi, not sure why shared dictionary not work at your way.

But actually, you can remove the resty lock. The lock just prevent unnecessary duplicate initialization under single worker for there is coroutine switch under concurrent scenario. 

please check if following works.

function _M.init_slots(self)
    if slot_cache[self.config.name] then
        return
    end

    self:fetch_slots()
end

**Comment by vkozubal** [comment]
Hello.
I have found that 
https://github.com/openresty/stream-lua-nginx-module/issues/25
`lua_shared_dict` is still not available in `stream_lua_nginx_module` unfortunately I think that is an issue.
