### ISSUE TITLE
require "redis" is not clear

### ISSUE THREAD

**Issue by hbagdi** [steve0511/resty-redis-cluster#5]
Hi Steve,
Thanks for your open-source work.

I've a question about the following line:
https://github.com/steve0511/resty-redis-cluster/blob/master/lib/rediscluster.lua#L69

Should this not be 'resty.redis'?
```
local redis = require "resty.redis"
```

**Comment by steve0511** [comment]
Hi,  thanks for the advice. Yes you are right,  resty.redis is more clear, I will change it.
