### ISSUE TITLE
Database select

### ISSUE THREAD

**Issue by i2dcarrasco** [steve0511/resty-redis-cluster#57]
Hello,

I'm starting to use this module and I finally was able to make it work, but I've noticed that there's no option to select the database (or at least is not documented and select() function doesn't work), so it always uses the 0 database.

Is there any way to change the database?

Best regards.

**Comment by toredash** [comment]
redis cluster does not have the concept of databases: 

> When using Redis Cluster, the SELECT command cannot be used, since Redis Cluster only supports database zero.

https://redis.io/commands/select

**Comment by i2dcarrasco** [comment]
I see... I like the way that databases separates the keys, but I'll have to change my mind.

Thanks!!
