### ISSUE TITLE
Redis compatibility version?

### ISSUE THREAD

**Issue by hbagdi** [steve0511/resty-redis-cluster#6]
Have you tested this library against a set of Redis versions?

I get the following error- 
attempt to get length of a number value
on this line: https://github.com/steve0511/resty-redis-cluster/blob/master/lib/rediscluster.lua#L431
```
2017/09/28 00:31:02 [error] 52#0: *1598 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/rediscluster.lua:431: attempt to get length of a number value
stack traceback:
coroutine 0:
	/usr/local/openresty/lualib/rediscluster.lua: in function 'hasClusterFailSignalInPipeline'
	/usr/local/openresty/lualib/rediscluster.lua:530: in function 'commit_pipeline'
```

**Comment by hbagdi** [comment]
Also, if it helps in any ways, I'm using the following version-
```
Redis server v=3.2.7 sha=00000000:0 malloc=jemalloc-4.4.0 bits=64 build=4b4d638eb6ec5175
```

Also, I execute the following (in a pipeline) when I get the above err-
```
red_cluster:incrby(cache_key, value)
red_cluster:expire(cache_key, EXPIRATIONS[period])
```

**Comment by steve0511** [comment]
HI, my test environment is Redis 3.2.8, but I think Redis 3.x shall have same behavior for there is no different with response protocol.

Can you please provide your Redis version? Meanwhile if possible please share your test code,
or add log to print that res would be helpful:

local function hasClusterFailSignalInPipeline(res)
   ngx.log(ngx.NOTICE, "res is "..cjson.encode(res)
    for i = 1, #res do
        if res[i] ~= ngx.null then
            for j = 1, #res[i] do
                if type(res[i][j]) == "string" and string.sub(res[i][j], 1, 11) == "CLUSTERDOWN" then
                    return true
                end
            end
        end
    end
    return false
end

**Comment by steve0511** [comment]
Hi, thanks very much for a good catch.

We do have an issue while parsing **Integer** type of redis response, I have fixed in the latest code.

Please use the latest code to test. And also please just note, incrby is an read/write operation and is not allowed in slave node, so just make sure **not to set enableSlaveRead**

**Comment by hbagdi** [comment]
Fixed in https://github.com/steve0511/resty-redis-cluster/commit/37d475d42c168bf2630d2fb5dfcbea9df95121a6
