### ISSUE TITLE
failed to create lock in initialization slot cache

### ISSUE THREAD

**Issue by HYHRainman** [steve0511/resty-redis-cluster#64]
2020/07/06 06:22:31 [error] 6#0: *32 [lua] rediscluster.lua:221: init_slots(): failed to create lock in initialization slot cache: dictionary not found, client: 192.168.16.1, server: , request: "GET / HTTP/1.0", host: "upstream_server"
2020/07/06 06:22:31 [error] 6#0: *32 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/project/application.lua:25: attempt to index local 'red_c' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/openresty/lualib/project/application.lua: in main chunk, client: 192.168.16.1, server: , request: "GET / HTTP/1.0", host: "upstream_server"

**Comment by toredash** [comment]
I believe you have forgot to add this to your nginx.conf file:
```
lua_shared_dict redis_cluster_slot_locks 100k;
```

**Comment by HYHRainman** [comment]
@toredash thanks

**Comment by toredash** [comment]
@HYHRainman did it work ? If so please close the issue
