### ISSUE TITLE
math.randomseed() must be called in init_worker context

### ISSUE THREAD

**Issue by hbagdi** [steve0511/resty-redis-cluster#7]
I'm not sure if we can really fix this issue and this might not be a problem inn most cases.
Thoughts?

```
2017/09/28 15:45:24 [warn] 45#0: [lua] globalpatches.lua:214: randomseed(): math.randomseed() must be called in init_worker context
stack traceback:
        /usr/local/openresty/lualib/rediscluster.lua:175: in main chunk
```

**Comment by steve0511** [comment]
Hi Harry

            It's odd we didn't encounter this warning. Looks like no impact on usage.

            My environment: nginx version: nginx/1.10.2
                           built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
                           built with OpenSSL 1.0.1u  22 Sep 2016
            Luajit version:2.1.0
            
            lua-nginx-module: v.0.10.7
 
Thanks

**Comment by hbagdi** [comment]
I'm closing this for now since it has no impact on usage.
Will re-open if needed.
