### ISSUE TITLE
redis_slot.c missing from repo

### ISSUE THREAD

**Issue by ledzepp4eva** [steve0511/resty-redis-cluster#75]
Hey,
I have managed to find the following commit https://github.com/steve0511/resty-redis-cluster/commit/6a9af0b17d150f27117e1867f3b44b5f4b7f566a

However this file doesn't appear to exist in the repo in master or the latest version 1.02. Is there a reason this is missing or can it be re-added?

Thanks,
Liam

**Comment by ledzepp4eva** [comment]
Ah I'm wondering that I should be using https://github.com/steve0511/resty-redis-cluster/blob/master/rockspec/resty-redis-cluster-1.02-4.rockspec for the install.

**Comment by ledzepp4eva** [comment]
I think it was moved to xmodem.lua here: https://github.com/steve0511/resty-redis-cluster/commit/b546dcbc311a37ed646d6a9278d83f1bf688a384

**Comment by steve0511** [comment]
Yes, just aware of that readme is not updated to latest.
