### ISSUE TITLE
 failed to create lock in initialization slot cache: dictionary not found, 

### ISSUE THREAD

**Issue by CosmosNi** [steve0511/resty-redis-cluster#77]
2020/12/11 20:53:11 [error] 10372#20888: *17 [lua] rediscluster.lua:232: init_slots(): failed to create lock in initialization slot cache: dictionary not found, client: 127.0.0.1, server: localhost, request: "GET /lua2 HTTP/1.1", host: "127.0.0.1:8000"
2020/12/11 20:53:11 [error] 10372#20888: *17 lua entry thread aborted: runtime error: ./test/hello.lua:19: attempt to index local 'red_c' (a nil value).

can you help me?

**Comment by raventide** [comment]
@steve0511 
same problem, need help

**Comment by toredash** [comment]
Please post nginx config

**Comment by raventide** [comment]
`http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen  9999;
        server_name  localhost;
        location /fmp4 {
            root /tmp/fmp4;
        }
    }

    lua_package_path "/xxx/lualib/?.lua;/xxx/lualib/resty/?.lua;";
    lua_shared_dict redis_cluster_slot_locks 100k;

    server {
        listen 3721;

        location /init {
            default_type text/html;
            content_by_lua_file /xxx/init.lua;
        }
    }
}`

> Please post nginx config
this is my http block

**Comment by toredash** [comment]
Not enough information provided. Suggest you read through the sample usage first at https://github.com/steve0511/resty-redis-cluster#sample-usage

**Comment by raventide** [comment]
`user root;

master_process off;
daemon off;
error_log stderr warn;
error_log /xxx/infolog.log info;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    lua_package_path "/xxx/lualib/?.lua;/xxx/lualib/resty/?.lua;";
    lua_shared_dict redis_cluster_slot_locks 100k;

    server {
        listen 3721;

        location /init {
            default_type text/html;
            content_by_lua_block {
                local config = {
                    dict_name = "test_locks",               --shared dictionary name for locks
                    name = "testCluster",                   --rediscluster name
                    serv_list = {                           --redis cluster node list(host and port),
                        { ip = "127.0.0.1", port = 7001 },
                        { ip = "127.0.0.1", port = 7002 },
                        { ip = "127.0.0.1", port = 7003 },
                        { ip = "127.0.0.1", port = 7004 },
                        { ip = "127.0.0.1", port = 7005 },
                        { ip = "127.0.0.1", port = 7000 }
                    },
                    keepalive_timeout = 60000,              --redis connection pool idle timeout
                    keepalive_cons = 1000,                  --redis connection pool size
                    connect_timeout = 1000,              --timeout while connecting
                    max_redirection = 5,                    --maximum retry attempts for redirection
                    max_connection_attempts = 1             --maximum retry attempts for connection
                }

                local redis_cluster = require "rediscluster"
                local red_c, err = redis_cluster:new(config)

                if err then
                    ngx.log(ngx.ERR, "err: ", err)
                end

                local v, err = red_c:get("name")
                if err then
                    ngx.log(ngx.ERR, "err: ", err)
                else
                    ngx.say(v)
                end
            }
        }
    }
}`

@toredash  okay, i paste it all

**Comment by toredash** [comment]
Remove this line:
```
dict_name = "test_locks",               --shared dictionary name for locks
```

The sample usage is not to great here since it override the default value, but does not explain why:
https://github.com/steve0511/resty-redis-cluster/blob/master/lib/resty/rediscluster.lua#L22
