### ISSUE TITLE
Auto-refresh support and cluster discovery support?

### ISSUE THREAD

**Issue by hbagdi** [steve0511/resty-redis-cluster#8]
Hi @steve0511,
 I've the read the code,  but I want to confirm the following:
1. Do we need to provide all the nodes of a cluster when we initially initialize the plugin? If only a single node is provided, will the library figure out other nodes and keep those nodes in it's configuration (in case the 1st one goes down or if the first node is not a master)?

2. How is failover handled? Suppose we've a 3 node redis cluster and we provide the 3 nodes in configuration, after some time, gradually, the 3 nodes die (not at the same time) and every time a node dies, another one is brought up. In such a case, will the library keep discovering these new nodes and work seamlessly?

**Comment by steve0511** [comment]
Hi @hbagdi 

       We use **"cluster slots"**  to discover the topological structure of all nodes(like ip, port, range of slots are charged of). **cluster slots** can execute on any node of your cluster, so actually, we can even just configure 1 node in the initial serv_list, and client will initial all the slot mapping by this node.
       Taking an example: You have 127.0.0.1 7001-7009 as a cluster. 7001, 7004, 7007 are master and others are slave. So even the following still works:

```
local config = {
    name = "testCluster",
    serv_list = {
        { ip = "127.0.0.1", port = 7001 }
    },
    keepalive_timeout = 60000,
    keepalive_cons = 1000,
    connection_timout = 1000,
    max_redirection = 5
}

local redis_cluster = require "rediscluster"
local red_c = redis_cluster:new(config)

```
      But we still recommend to configure as more nodes. There might be node failure or connection
issue, while we initial or reset the slot mapping, client iterates each pre-configured nodes to execute "cluster slots" until there is one successful response. 

     About failover question, you might see each time clients get connection issue and then we will re-initialize the slot mapping.  So consider following two scenario:

1). you have 3*2 nodes(3 master, each 1 replica) and 1 master of them down, the slave get promoted, client will get connection error with old master and eventually re-initial the slot mapping, update the mapping with correct one: 3 master, only 2 of them has 1 replica

2). You have 3*2 nodes(3 master, each 1 replica) and 1 master and its replica are all down. By default, redis-cluster has "cluster-require-full-coverage" set as true, so now the redis-cluster is regarded as **failed**  status. Then client will directly catch and throw the error response. 
    Then you might have 3 ways to fix the error:
    i. directly  execute **redis-trib.rb fix** and  now you have the rest 2 masters with replica to cover all the slots. Then you might encounter the "**MOVED redirection**" since there is slots still mapped to old node which is down in our slotmapping. We will re-initial the mapping when we get any "MOVED redirection".

   ii. restart the failed nodes with original ip, port. I don't think any problem here.

   iii. start another node with other ip,port, add it to cluster, execute **"redis-trib.rb fix"**, this is somewhat same case with i.

       Hopes this helps!

**Comment by hbagdi** [comment]
Hi @steve0511 

Thanks for your detailed answer to my question.
You're very kind.

Reading the code, I had figured the same thing out what you mentioned but I needed a confirmation before going ahead.

Thanks a lot for clearing my doubts.
