### ISSUE TITLE
运行的时候报错了

### ISSUE THREAD

**Issue by dahaigit** [steve0511/resty-redis-cluster#83]
2021/03/27 02:27:36 [error] 7#0: *1 [lua] rediscluster.lua:257: init_slots(): failed to create lock in initialization slot cache: dictionary not found, client: 220.234.141.60, server: , request: "GET / HTTP/1.1", host: "...:8002"
2021/03/27 02:27:36 [error] 7#0: *1 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/project/common/application.lua:25: attempt to index local 'red_c' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/openresty/lualib/project/common/application.lua: in main chunk, client: ... server: , request: "GET / HTTP/1.1", host: "...::8002"

**Comment by LingXi1420** [comment]
I met this problem too,, How did you deal with this problem?   - -
